#pragma once
// Make "signals:", "slots:" visible as access specifiers
#define QT_ANNOTATE_ACCESS_SPECIFIER(a) __attribute__((annotate(#a)))
#include <qgsspatialindexkdbush.h>
#include <qgsmaptopixelgeometrysimplifier.h>
#include <qgscoordinateformatter.h>
#include <qgscacheindex.h>
#include <raster/qgsrasterviewport.h>
#include <raster/qgslinearminmaxenhancement.h>
#include <raster/qgsrasterinterface.h>
#include <raster/qgshuesaturationfilter.h>
#include <raster/qgsrasterattributetable.h>
#include <raster/qgsmultibandcolorrenderer.h>
#include <raster/qgsrasterdataprovider.h>
#include <raster/qgscliptominmaxenhancement.h>
#include <raster/qgsrasternuller.h>
#include <raster/qgsrasterminmaxorigin.h>
#include <raster/qgsrastercontourrenderer.h>
#include <raster/qgsrasterdataprovidertemporalcapabilities.h>
#include <raster/qgsrasterlayerelevationproperties.h>
#include <raster/qgspalettedrasterrenderer.h>
#include <raster/qgsrasterresampler.h>
#include <raster/qgsrasterblock.h>
#include <raster/qgscontrastenhancementfunction.h>
#include <raster/qgsrastershaderfunction.h>
#include <raster/qgsbilinearrasterresampler.h>
#include <raster/qgsraster.h>
#include <raster/qgsrasterfilewritertask.h>
#include <raster/qgscontrastenhancement.h>
#include <raster/qgshillshaderenderer.h>
#include <raster/qgsbrightnesscontrastfilter.h>
#include <raster/qgsrasterpipe.h>
#include <raster/qgsrasterprojector.h>
#include <raster/qgssinglebandcolordatarenderer.h>
#include <raster/qgsrasterrendererutils.h>
#include <raster/qgsexiftools.h>
#include <raster/qgscubicrasterresampler.h>
#include <raster/qgsrasterrenderer.h>
#include <raster/qgsrasterrange.h>
#include <raster/qgscolorrampshader.h>
#include <raster/qgsrastershader.h>
#include <raster/qgsrasterpyramid.h>
#include <raster/qgsrasteriterator.h>
#include <raster/qgslinearminmaxenhancementwithclip.h>
#include <raster/qgsrasterchecker.h>
#include <raster/qgssinglebandgrayrenderer.h>
#include <raster/qgsrasterfilewriter.h>
#include <raster/qgsrasterdrawer.h>
#include <raster/qgsrasterlayertemporalproperties.h>
#include <raster/qgsrasterresamplefilter.h>
#include <raster/qgssinglebandpseudocolorrenderer.h>
#include <raster/qgsrasterbandstats.h>
#include <raster/qgsrastertransparency.h>
#include <raster/qgsrasterlayer.h>
#include <raster/qgsrasteridentifyresult.h>
#include <raster/qgsrasterhistogram.h>
#include <qgsvectorfilewriter.h>
#include <qgsjsonutils.h>
#include <scalebar/qgssteppedlinescalebarrenderer.h>
#include <scalebar/qgsticksscalebarrenderer.h>
#include <scalebar/qgsscalebarrendererregistry.h>
#include <scalebar/qgsnumericscalebarrenderer.h>
#include <scalebar/qgsscalebarrenderer.h>
#include <scalebar/qgsscalebarsettings.h>
#include <scalebar/qgsdoubleboxscalebarrenderer.h>
#include <scalebar/qgshollowscalebarrenderer.h>
#include <scalebar/qgssingleboxscalebarrenderer.h>
#include <3d/qgsabstractpointcloud3drenderer.h>
#include <3d/qgs3drendererregistry.h>
#include <3d/qgs3dsymbolregistry.h>
#include <3d/qgsabstract3drenderer.h>
#include <3d/qgsabstract3dsymbol.h>
#include <qgsvectorsimplifymethod.h>
#include <qgspluginlayerregistry.h>
#include <qgssourcecache.h>
#include <qgsmapclippingregion.h>
#include <qgsmapsettingsutils.h>
#include <qgsfeaturerequest.h>
#include <qgscolorscheme.h>
#include <qgsmapsettings.h>
#include <qgsrange.h>
#include <qgstestutils.h>
#include <qgsfeaturepickermodelbase.h>
#include <qgsvector3d.h>
#include <browser/qgsdataitemprovider.h>
#include <browser/qgsdatacollectionitem.h>
#include <browser/qgszipitem.h>
#include <browser/qgsdirectoryitem.h>
#include <browser/qgsbrowserproxymodel.h>
#include <browser/qgslayeritem.h>
#include <browser/qgsdataitem.h>
#include <browser/qgsdataitemproviderregistry.h>
#include <browser/qgsprojectitem.h>
#include <browser/qgsfielddomainsitem.h>
#include <browser/qgsfieldsitem.h>
#include <browser/qgsrelationshipsitem.h>
#include <browser/qgsconnectionsitem.h>
#include <browser/qgsdatabaseschemaitem.h>
#include <browser/qgsbrowsermodel.h>
#include <browser/qgsfavoritesitem.h>
#include <qgsfeaturepickermodel.h>
#include <qgsfilefiltergenerator.h>
#include <numericformats/qgsnumericformatregistry.h>
#include <numericformats/qgscurrencynumericformat.h>
#include <numericformats/qgspercentagenumericformat.h>
#include <numericformats/qgsnumericformat.h>
#include <numericformats/qgsbasicnumericformat.h>
#include <numericformats/qgsbearingnumericformat.h>
#include <numericformats/qgsfractionnumericformat.h>
#include <numericformats/qgsfallbacknumericformat.h>
#include <numericformats/qgsscientificnumericformat.h>
#include <numericformats/qgscoordinatenumericformat.h>
#include <qgseditorwidgetsetup.h>
#include <qgsstoredexpressionmanager.h>
#include <qgsimagecache.h>
#include <proj/qgscoordinatetransform.h>
#include <proj/qgscoordinatereferencesystemregistry.h>
#include <proj/qgsdatums.h>
#include <proj/qgsprojutils.h>
#include <proj/qgscelestialbody.h>
#include <proj/qgsellipsoidutils.h>
#include <proj/qgscoordinatereferencesystemutils.h>
#include <proj/qgsprojectionfactors.h>
#include <proj/qgscoordinatetransformcontext.h>
#include <proj/qgsdatumtransform.h>
#include <proj/qgscoordinatereferencesystem.h>
#include <proj/qgsprojoperation.h>
#include <qgsmessageoutput.h>
#include <maprenderer/qgsmaprenderercustompainterjob.h>
#include <maprenderer/qgsmaprenderertask.h>
#include <maprenderer/qgsmaprendererjob.h>
#include <maprenderer/qgsmaprendererparalleljob.h>
#include <maprenderer/qgsmaprenderersequentialjob.h>
#include <maprenderer/qgsrendereditemresults.h>
#include <maprenderer/qgsmaprenderercache.h>
#include <qgspythonrunner.h>
#include <qgsrunprocess.h>
#include <qgstemporalrangeobject.h>
#include <qgsvectorfilewritertask.h>
#include <qgscadutils.h>
#include <metadata/qgslayermetadataformatter.h>
#include <metadata/qgslayermetadata.h>
#include <metadata/qgsabstractlayermetadataprovider.h>
#include <metadata/qgsabstractmetadatabase.h>
#include <metadata/qgsmetadatautils.h>
#include <metadata/qgslayermetadataproviderregistry.h>
#include <metadata/qgsprojectmetadata.h>
#include <metadata/qgslayermetadatavalidator.h>
#include <locator/qgslocatormodelbridge.h>
#include <locator/qgslocator.h>
#include <locator/qgslocatorfilter.h>
#include <locator/qgslocatorcontext.h>
#include <locator/qgslocatormodel.h>
#include <qgsogcutils.h>
#include <qgsselectioncontext.h>
#include <qgsgeometryvalidator.h>
#include <qgsfeatureiterator.h>
#include <qgsziputils.h>
#include <qgsdefaultvalue.h>
#include <qgstemporalcontroller.h>
#include <qgsvirtuallayertask.h>
#include <qgsgmlschema.h>
#include <auth/qgsauthmanager.h>
#include <auth/qgsauthconfig.h>
#include <auth/qgsauthcertutils.h>
#include <auth/qgsauthmethod.h>
#include <qgshtmlutils.h>
#include <qgsmargins.h>
#include <qgsfieldproxymodel.h>
#include <fieldformatter/qgsfallbackfieldformatter.h>
#include <fieldformatter/qgslistfieldformatter.h>
#include <fieldformatter/qgsvaluemapfieldformatter.h>
#include <fieldformatter/qgsdatetimefieldformatter.h>
#include <fieldformatter/qgscheckboxfieldformatter.h>
#include <fieldformatter/qgsrelationreferencefieldformatter.h>
#include <fieldformatter/qgsvaluerelationfieldformatter.h>
#include <fieldformatter/qgskeyvaluefieldformatter.h>
#include <fieldformatter/qgsrangefieldformatter.h>
#include <qgsmaplayerserverproperties.h>
#include <qgsdatabasetablemodel.h>
#include <qgscolorutils.h>
#include <qgsoptional.h>
#include <project/qgsprojectgpssettings.h>
#include <project/qgsproject.h>
#include <project/qgsprojectviewsettings.h>
#include <project/qgsprojectstylesettings.h>
#include <project/qgsprojectproperty.h>
#include <project/qgsprojectstorageregistry.h>
#include <project/qgsprojectservervalidator.h>
#include <project/qgsprojectelevationproperties.h>
#include <project/qgsprojectfiletransform.h>
#include <project/qgsmapviewsmanager.h>
#include <project/qgsprojectstorage.h>
#include <project/qgsprojectutils.h>
#include <project/qgsprojectdisplaysettings.h>
#include <project/qgsprojecttimesettings.h>
#include <project/qgsprojectbadlayerhandler.h>
#include <project/qgsprojectversion.h>
#include <project/qgsprojecttranslator.h>
#include <qgsrecentstylehandler.h>
#include <qgsmaplayermodel.h>
#include <qgsmaskidprovider.h>
#include <qgslegendsettings.h>
#include <qgsproviderconnectionmodel.h>
#include <qgsmaplayertemporalproperties.h>
#include <qgstemporalutils.h>
#include <qgsmapclippingutils.h>
#include <qgsexpressionfieldbuffer.h>
#include <qgsfontutils.h>
#include <qgsfields.h>
#include <qgsfeaturesource.h>
#include <geometry/qgscompoundcurve.h>
#include <geometry/qgsmultipolygon.h>
#include <geometry/qgsregularpolygon.h>
#include <geometry/qgsgeometrytransformer.h>
#include <geometry/qgsmultisurface.h>
#include <geometry/qgscurvepolygon.h>
#include <geometry/qgsquadrilateral.h>
#include <geometry/qgspoint.h>
#include <geometry/qgsabstractgeometry.h>
#include <geometry/qgslinesegment.h>
#include <geometry/qgswkbtypes.h>
#include <geometry/qgsmulticurve.h>
#include <geometry/qgscircularstring.h>
#include <geometry/qgspolygon.h>
#include <geometry/qgsgeometryengine.h>
#include <geometry/qgsmultilinestring.h>
#include <geometry/qgscircle.h>
#include <geometry/qgsellipse.h>
#include <geometry/qgslinestring.h>
#include <geometry/qgssurface.h>
#include <geometry/qgsvertexid.h>
#include <geometry/qgsmultipoint.h>
#include <geometry/qgsgeometry.h>
#include <geometry/qgsgeometrycollection.h>
#include <geometry/qgsray3d.h>
#include <geometry/qgsgeometryutils.h>
#include <geometry/qgscurve.h>
#include <geometry/qgsbox3d.h>
#include <geometry/qgsreferencedgeometry.h>
#include <geometry/qgsrectangle.h>
#include <geometry/qgswkbptr.h>
#include <geometry/qgstriangle.h>
#include <qgsfileutils.h>
#include <qgsvirtuallayerdefinitionutils.h>
#include <qgsfieldformatter.h>
#include <qgsclipper.h>
#include <qgspainting.h>
#include <qgsnullpainterdevice.h>
#include <qgsremappingproxyfeaturesink.h>
#include <classification/qgsclassificationjenks.h>
#include <classification/qgsclassificationstandarddeviation.h>
#include <classification/qgsclassificationmethod.h>
#include <classification/qgsclassificationquantile.h>
#include <classification/qgsclassificationequalinterval.h>
#include <classification/qgsclassificationfixedinterval.h>
#include <classification/qgsclassificationprettybreaks.h>
#include <classification/qgsclassificationmethodregistry.h>
#include <classification/qgsclassificationlogarithmic.h>
#include <classification/qgsclassificationcustom.h>
#include <qgsrenderedfeaturehandlerinterface.h>
#include <qgsruntimeprofiler.h>
#include <qgsmaplayerdependency.h>
#include <qgspointlocator.h>
#include <qgsgeometrysimplifier.h>
#include <qgstracer.h>
#include <qgstaskmanager.h>
#include <qgsbookmarkmanager.h>
#include <qgscopyfiletask.h>
#include <qgsgeometryoptions.h>
#include <qgshstoreutils.h>
#include <qgssingleitemmodel.h>
#include <network/qgsnewsfeedmodel.h>
#include <network/qgsblockingnetworkrequest.h>
#include <network/qgsfiledownloader.h>
#include <network/qgsnetworkcontentfetcher.h>
#include <network/qgshttpheaders.h>
#include <network/qgsnetworkaccessmanager.h>
#include <network/qgsnetworkreply.h>
#include <network/qgsnetworkcontentfetchertask.h>
#include <network/qgsnewsfeedparser.h>
#include <network/qgsnetworkcontentfetcherregistry.h>
#include <qgssnappingutils.h>
#include <qgsfeedback.h>
#include <qgsstringstatisticalsummary.h>
#include <qgsproxyfeaturesink.h>
#include <qgsmaskpaintdevice.h>
#include <qgspointxy.h>
#include <qgstrackedvectorlayertools.h>
#include <qgsexpressioncontextgenerator.h>
#include <layout/qgslayoutitemregistry.h>
#include <layout/qgslayoutgridsettings.h>
#include <layout/qgslayoutnortharrowhandler.h>
#include <layout/qgslayoutmanager.h>
#include <layout/qgslayoutitemmap.h>
#include <layout/qgslayoutitempolygon.h>
#include <layout/qgslayoutatlas.h>
#include <layout/qgsprintlayout.h>
#include <layout/qgslayouteffect.h>
#include <layout/qgslayout.h>
#include <layout/qgslayoutitemhtml.h>
#include <layout/qgslayoutitemnodeitem.h>
#include <layout/qgslayoutserializableobject.h>
#include <layout/qgslayoutsize.h>
#include <layout/qgslayoutundostack.h>
#include <layout/qgslayoutpoint.h>
#include <layout/qgslayoutitemtexttable.h>
#include <layout/qgslayoutitempicture.h>
#include <layout/qgslayoututils.h>
#include <layout/qgsreport.h>
#include <layout/qgslayoutitemlegend.h>
#include <layout/qgslayoutobject.h>
#include <layout/qgslayoutitemmapoverview.h>
#include <layout/qgslayoutitemmanualtable.h>
#include <layout/qgsabstractlayoutiterator.h>
#include <layout/qgslayoutitem.h>
#include <layout/qgsreportsectionfieldgroup.h>
#include <layout/qgslayoutundocommand.h>
#include <layout/qgslayoutitemscalebar.h>
#include <layout/qgslayoutitempage.h>
#include <layout/qgslayoutmodel.h>
#include <layout/qgslayoutitemattributetable.h>
#include <layout/qgsabstractreportsection.h>
#include <layout/qgsreportsectionlayout.h>
#include <layout/qgslayoutaligner.h>
#include <layout/qgslayoutsnapper.h>
#include <layout/qgslayouttable.h>
#include <layout/qgslayoutmeasurement.h>
#include <layout/qgslayoutitemlabel.h>
#include <layout/qgslayoutmultiframe.h>
#include <layout/qgslayoutframe.h>
#include <layout/qgslayoutitemelevationprofile.h>
#include <layout/qgslayoutrendercontext.h>
#include <layout/qgslayoutmeasurementconverter.h>
#include <layout/qgslayoutpagecollection.h>
#include <layout/qgslayouttablecolumn.h>
#include <layout/qgslayoutexporter.h>
#include <layout/qgsmasterlayoutinterface.h>
#include <layout/qgslayoutitemmapitem.h>
#include <layout/qgslayoutguidecollection.h>
#include <layout/qgslayoutitemshape.h>
#include <layout/qgslayoutitemmarker.h>
#include <layout/qgspagesizeregistry.h>
#include <layout/qgslayoutreportcontext.h>
#include <layout/qgslayoutitempolyline.h>
#include <layout/qgslayoutitemgroup.h>
#include <layout/qgslayoutitemmapgrid.h>
#include <qgscolorramp.h>
#include <qgstablecell.h>
#include <qgsconditionalstyle.h>
#include <callouts/qgscallout.h>
#include <callouts/qgscalloutsregistry.h>
#include <qgsconnectionregistry.h>
#include <mesh/qgsmeshlayerinterpolator.h>
#include <mesh/qgsmeshdataset.h>
#include <mesh/qgsmeshlayer.h>
#include <mesh/qgsmeshlayertemporalproperties.h>
#include <mesh/qgsmeshtracerenderer.h>
#include <mesh/qgsmeshspatialindex.h>
#include <mesh/qgsmeshforcebypolylines.h>
#include <mesh/qgsmesh3daveraging.h>
#include <mesh/qgsmeshcalculator.h>
#include <mesh/qgsmeshdataprovider.h>
#include <mesh/qgsmeshlayerelevationproperties.h>
#include <mesh/qgsmeshdataprovidertemporalcapabilities.h>
#include <mesh/qgsmeshtimesettings.h>
#include <mesh/qgsmesheditor.h>
#include <mesh/qgsmeshrenderersettings.h>
#include <mesh/qgsmeshadvancedediting.h>
#include <qgsidentifycontext.h>
#include <validity/qgsvaliditycheckregistry.h>
#include <validity/qgsvaliditycheckcontext.h>
#include <validity/qgsabstractvaliditycheck.h>
#include <qgselevationmap.h>
#include <qgsdatetimestatisticalsummary.h>
#include <qgsfeatureid.h>
#include <gps/qgsbabelformat.h>
#include <gps/qgsnmeaconnection.h>
#include <gps/qgsgpsdetector.h>
#include <gps/qgsgpslogger.h>
#include <gps/qgsgpsconnection.h>
#include <gps/qgsvectorlayergpslogger.h>
#include <gps/qgsgpsdconnection.h>
#include <gps/qgsbabelformatregistry.h>
#include <gps/qgsbabelgpsdevice.h>
#include <gps/qgsgpsinformation.h>
#include <gps/qgsgpsconnectionregistry.h>
#include <gps/qgsqtlocationconnection.h>
#include <gps/qgssatelliteinformation.h>
#include <qgsfeaturestore.h>
#include <qgstolerance.h>
#include <qgselevationshadingrenderer.h>
#include <qgsmaplayer.h>
#include <qgsmimedatautils.h>
#include <qgslegendstyle.h>
#include <qgsmaplayerstyle.h>
#include <settings/qgssettings.h>
#include <settings/qgssettingstreenode.h>
#include <settings/qgssettingsentry.h>
#include <settings/qgssettingstree.h>
#include <settings/qgssettingsentryimpl.h>
#include <settings/qgssettingsregistrycore.h>
#include <settings/qgssettingsentrygroup.h>
#include <settings/qgssettingsregistry.h>
#include <qgsauxiliarystorage.h>
#include <qgsmaplayerrenderer.h>
#include <qgselevationutils.h>
#include <qgsattributetableconfig.h>
#include <qgsscalecalculator.h>
#include <qgslocaldefaultsettings.h>
#include <qgsiconutils.h>
#include <qgssqliteutils.h>
#include <qgsfieldmodel.h>
#include <textrenderer/qgstextmasksettings.h>
#include <textrenderer/qgsfontmanager.h>
#include <textrenderer/qgstextbackgroundsettings.h>
#include <textrenderer/qgstextformat.h>
#include <textrenderer/qgstextrenderer.h>
#include <textrenderer/qgstextblock.h>
#include <textrenderer/qgstextfragment.h>
#include <textrenderer/qgstextcharacterformat.h>
#include <textrenderer/qgstextbuffersettings.h>
#include <textrenderer/qgstextdocumentmetrics.h>
#include <textrenderer/qgstextrendererutils.h>
#include <textrenderer/qgstextshadowsettings.h>
#include <textrenderer/qgstextdocument.h>
#include <expression/qgsexpressionnode.h>
#include <expression/qgsexpressionnodeimpl.h>
#include <expression/qgsexpression.h>
#include <expression/qgsexpressionfunction.h>
#include <expression/qgsexpressioncontextutils.h>
#include <qgslayernotesutils.h>
#include <qgsspatialindexkdbushdata.h>
#include <qgsspatialindex.h>
#include <qgsrenderchecker.h>
#include <qgstessellator.h>
#include <editform/qgsattributeeditortextelement.h>
#include <editform/qgsattributeeditorelement.h>
#include <editform/qgseditformconfig.h>
#include <editform/qgsattributeeditorhtmlelement.h>
#include <editform/qgsattributeeditorfield.h>
#include <editform/qgsattributeeditorqmlelement.h>
#include <editform/qgsattributeeditorcontainer.h>
#include <editform/qgsattributeeditoraction.h>
#include <editform/qgsattributeeditorspacerelement.h>
#include <editform/qgsattributeeditorrelation.h>
#include <symbology/qgsrendererrange.h>
#include <symbology/qgs25drenderer.h>
#include <symbology/qgsgraduatedsymbolrenderer.h>
#include <symbology/qgscombinedstylemodel.h>
#include <symbology/qgsheatmaprenderer.h>
#include <symbology/qgscategorizedsymbolrenderer.h>
#include <symbology/qgsmarkersymbol.h>
#include <symbology/qgsstyle.h>
#include <symbology/qgsstyleentityvisitor.h>
#include <symbology/qgsembeddedsymbolrenderer.h>
#include <symbology/qgsgeometrygeneratorsymbollayer.h>
#include <symbology/qgsfeaturerenderergenerator.h>
#include <symbology/qgsarrowsymbollayer.h>
#include <symbology/qgsmarkersymbollayer.h>
#include <symbology/qgssymbollayerregistry.h>
#include <symbology/qgsinterpolatedlinerenderer.h>
#include <symbology/qgsvectorfieldsymbollayer.h>
#include <symbology/qgscolorbrewerpalette.h>
#include <symbology/qgslinesymbol.h>
#include <symbology/qgslinesymbollayer.h>
#include <symbology/qgspointclusterrenderer.h>
#include <symbology/qgsmergedfeaturerenderer.h>
#include <symbology/qgsellipsesymbollayer.h>
#include <symbology/qgssymbollayerreference.h>
#include <symbology/qgssymbol.h>
#include <symbology/qgsrendererregistry.h>
#include <symbology/qgsnullsymbolrenderer.h>
#include <symbology/qgspointdisplacementrenderer.h>
#include <symbology/qgssvgcache.h>
#include <symbology/qgsstylemodel.h>
#include <symbology/qgsmapinfosymbolconverter.h>
#include <symbology/qgssymbolrendercontext.h>
#include <symbology/qgspointdistancerenderer.h>
#include <symbology/qgscptcityarchive.h>
#include <symbology/qgslegendsymbolitem.h>
#include <symbology/qgsfillsymbollayer.h>
#include <symbology/qgsinvertedpolygonrenderer.h>
#include <symbology/qgsrulebasedrenderer.h>
#include <symbology/qgsfillsymbol.h>
#include <symbology/qgssinglesymbolrenderer.h>
#include <symbology/qgssymbollayerutils.h>
#include <symbology/qgsmasksymbollayer.h>
#include <symbology/qgsrenderer.h>
#include <symbology/qgssymbollayer.h>
#include <qgspropertycollection.h>
#include <qgsmaplayerutils.h>
#include <qgstranslationcontext.h>
#include <qgsarchive.h>
#include <qgsdataprovidertemporalcapabilities.h>
#include <qgsrendereditemdetails.h>
#include <qgsproperty.h>
#include <qgsinterval.h>
#include <qgsbookmarkmodel.h>
#include <qgsmultirenderchecker.h>
#include <qgspluginlayer.h>
#include <qgsmaplayerstylemanager.h>
#include <qgslegendrenderer.h>
#include <qgsbearingutils.h>
#include <effects/qgsblureffect.h>
#include <effects/qgspainteffect.h>
#include <effects/qgstransformeffect.h>
#include <effects/qgsimageoperation.h>
#include <effects/qgsgloweffect.h>
#include <effects/qgsshadoweffect.h>
#include <effects/qgspainteffectregistry.h>
#include <effects/qgscoloreffect.h>
#include <effects/qgseffectstack.h>
#include <geocoding/qgsgeocodercontext.h>
#include <geocoding/qgsgeocoder.h>
#include <geocoding/qgsabstractgeocoderlocatorfilter.h>
#include <geocoding/qgsgeocoderresult.h>
#include <geocoding/qgsnominatimgeocoder.h>
#include <geocoding/qgsgooglemapsgeocoder.h>
#include <qgsmapthemecollection.h>
#include <qgsfeaturesink.h>
#include <qgstransaction.h>
#include <qgslogger.h>
#include <pointcloud/qgspointcloudblock.h>
#include <pointcloud/qgspointcloudlayerexporter.h>
#include <pointcloud/qgspointcloudattributebyramprenderer.h>
#include <pointcloud/qgspointcloudrenderer.h>
#include <pointcloud/qgspointcloudrgbrenderer.h>
#include <pointcloud/qgspointcloudextentrenderer.h>
#include <pointcloud/qgspointcloudlayer.h>
#include <pointcloud/qgspointcloudclassifiedrenderer.h>
#include <pointcloud/qgspointcloudrendererregistry.h>
#include <pointcloud/qgspointcloudlayerelevationproperties.h>
#include <pointcloud/qgspointclouddataprovider.h>
#include <pointcloud/qgspointcloudattribute.h>
#include <pointcloud/qgspointcloudattributemodel.h>
#include <pointcloud/qgspointcloudstatistics.h>
#include <qgshistogram.h>
#include <qgsproxyprogresstask.h>
#include <qgsuserprofile.h>
#include <sensor/qgsabstractsensor.h>
#include <sensor/qgssensorregistry.h>
#include <sensor/qgssensormodel.h>
#include <sensor/qgsiodevicesensor.h>
#include <sensor/qgssensormanager.h>
#include <qgsrendercontext.h>
#include <qgsdbquerylog.h>
#include <qgserror.h>
#include <qgsofflineediting.h>
#include <qgsvector.h>
#include <qgssqlstatement.h>
#include <qgsstringutils.h>
#include <dxf/qgsdxfexport.h>
#include <qgsunsetattributevalue.h>
#include <elevation/qgsabstractprofilegenerator.h>
#include <elevation/qgsprofilerequest.h>
#include <elevation/qgsprofilerenderer.h>
#include <elevation/qgsabstractprofilesource.h>
#include <elevation/qgsterrainprovider.h>
#include <elevation/qgsprofilepoint.h>
#include <elevation/qgsprofilesnapping.h>
#include <qgsvirtuallayerdefinition.h>
#include <qgslocalizeddatapathregistry.h>
#include <vectortile/qgsvectortilelayer.h>
#include <vectortile/qgsvtpktiles.h>
#include <vectortile/qgsvectortilebasiclabeling.h>
#include <vectortile/qgsmapboxglstyleconverter.h>
#include <vectortile/qgsvectortilematrixset.h>
#include <vectortile/qgsvectortilerenderer.h>
#include <vectortile/qgsvectortilewriter.h>
#include <vectortile/qgsvectortilebasicrenderer.h>
#include <vectortile/qgsvectortilelabeling.h>
#include <qgsgrouplayer.h>
#include <qgis.h>
#include <qgsfieldformatterregistry.h>
#include <qgstransactiongroup.h>
#include <qgstiles.h>
#include <qgsdatabaseschemamodel.h>
#include <qgsreadwritelocker.h>
#include <actions/qgsactionscope.h>
#include <actions/qgsactionmanager.h>
#include <actions/qgsactionscoperegistry.h>
#include <actions/qgsaction.h>
#include <qgspathresolver.h>
#include <qgsdartmeasurement.h>
#include <qgsunittypes.h>
#include <qgsapplication.h>
#include <qgsrelation.h>
#include <qgssnappingconfig.h>
#include <qgsqueryresultmodel.h>
#include <qgscommandlineutils.h>
#include <providers/qgsprovidersublayermodel.h>
#include <providers/qgsproviderregistry.h>
#include <providers/qgsabstractdatabaseproviderconnection.h>
#include <providers/qgsprovidermetadata.h>
#include <providers/qgsabstractdbtablemodel.h>
#include <providers/qgsprovidersublayertask.h>
#include <providers/qgsprovidersqlquerybuilder.h>
#include <providers/qgsproviderutils.h>
#include <providers/qgsdataprovider.h>
#include <providers/qgsprovidersublayerdetails.h>
#include <providers/memory/qgsmemoryproviderutils.h>
#include <providers/qgsabstractproviderconnection.h>
#include <providers/arcgis/qgsarcgisportalutils.h>
#include <providers/arcgis/qgsarcgisrestutils.h>
#include <qgsowsconnection.h>
#include <qgsmaplayerelevationproperties.h>
#include <qgsdiagramrenderer.h>
#include <qgsweakrelation.h>
#include <qgscacheindexfeatureid.h>
#include <qgsoptionalexpression.h>
#include <qgspostgresstringutils.h>
#include <qgsmaptopixel.h>
#include <qgspropertytransformer.h>
#include <qgsmaphittest.h>
#include <externalstorage/qgsexternalstorageregistry.h>
#include <externalstorage/qgsexternalstorage.h>
#include <qgsrelationcontext.h>
#include <qgsmapunitscale.h>
#include <diagram/qgsdiagram.h>
#include <diagram/qgsstackedbardiagram.h>
#include <diagram/qgshistogramdiagram.h>
#include <diagram/qgspiediagram.h>
#include <diagram/qgstextdiagram.h>
#include <qgsdistancearea.h>
#include <vector/qgsvectorlayerfeaturecounter.h>
#include <vector/qgsvectorlayerjoinbuffer.h>
#include <vector/qgsvectorlayerundopassthroughcommand.h>
#include <vector/qgsvectorlayerundocommand.h>
#include <vector/qgsvectorlayerjoininfo.h>
#include <vector/qgsvectorlayertemporalproperties.h>
#include <vector/qgsvectorlayereditpassthrough.h>
#include <vector/qgsvectorlayertools.h>
#include <vector/qgsvectorlayer.h>
#include <vector/qgsfielddomain.h>
#include <vector/qgsvectordataprovider.h>
#include <vector/qgsvectorlayercache.h>
#include <vector/qgsvectorlayereditbuffergroup.h>
#include <vector/qgsvectorlayerutils.h>
#include <vector/qgsvectordataprovidertemporalcapabilities.h>
#include <vector/qgsvectorlayereditutils.h>
#include <vector/qgsvectorlayerexporter.h>
#include <vector/qgsvectorlayereditbuffer.h>
#include <vector/qgsvectorlayerelevationproperties.h>
#include <vector/qgsvectorlayerfeatureiterator.h>
#include <qgsmaplayerstore.h>
#include <qgscolorrampimpl.h>
#include <qgsfield.h>
#include <qgsrelationmanager.h>
#include <qgsattributes.h>
#include <qgssldexportcontext.h>
#include <qgsexpressioncontextscopegenerator.h>
#include <qgsfeaturefilterprovider.h>
#include <qgsmaplayerfactory.h>
#include <qgsmapdecoration.h>
#include <processing/qgsprocessingparametermeshdataset.h>
#include <processing/qgsprocessingoutputs.h>
#include <processing/qgsprocessingprovider.h>
#include <processing/qgsprocessingparameterdxflayers.h>
#include <processing/qgsprocessingbatch.h>
#include <processing/qgsprocessingalgrunnertask.h>
#include <processing/qgsprocessingparameterfieldmap.h>
#include <processing/qgsprocessingfeedback.h>
#include <processing/qgsprocessingregistry.h>
#include <processing/qgsprocessingparametervectortilewriterlayers.h>
#include <processing/qgsprocessingparameters.h>
#include <processing/qgsprocessingparametertype.h>
#include <processing/models/qgsprocessingmodelalgorithm.h>
#include <processing/models/qgsprocessingmodelcomment.h>
#include <processing/models/qgsprocessingmodeloutput.h>
#include <processing/models/qgsprocessingmodelchildalgorithm.h>
#include <processing/models/qgsprocessingmodelparameter.h>
#include <processing/models/qgsprocessingmodelgroupbox.h>
#include <processing/models/qgsprocessingmodelchilddependency.h>
#include <processing/models/qgsprocessingmodelcomponent.h>
#include <processing/models/qgsprocessingmodelchildparametersource.h>
#include <processing/qgsprocessingparameteraggregate.h>
#include <processing/qgsprocessingutils.h>
#include <processing/qgsprocessingparametertininputlayers.h>
#include <processing/qgsprocessingcontext.h>
#include <processing/qgsprocessingalgorithm.h>
#include <processing/qgsprocessing.h>
#include <qgslayerdefinition.h>
#include <qgsgml.h>
#include <plot/qgsplot.h>
#include <qgsfeature.h>
#include <qgsvariantutils.h>
#include <qgsstatisticalsummary.h>
#include <qgsanimatedicon.h>
#include <qgspolymorphicrelation.h>
#include <qgscachedfeatureiterator.h>
#include <qgsxmlutils.h>
#include <qgsuserprofilemanager.h>
#include <qgsmaplayerlegend.h>
#include <layertree/qgslayertreegroup.h>
#include <layertree/qgslayertreeutils.h>
#include <layertree/qgslayertreelayer.h>
#include <layertree/qgslayertreemodellegendnode.h>
#include <layertree/qgslayertreemodel.h>
#include <layertree/qgscolorramplegendnode.h>
#include <layertree/qgslayertree.h>
#include <layertree/qgslegendpatchshape.h>
#include <layertree/qgslayertreefiltersettings.h>
#include <layertree/qgscolorramplegendnodesettings.h>
#include <layertree/qgslayertreeregistrybridge.h>
#include <layertree/qgslayertreenode.h>
#include <layertree/qgslayertreefilterproxymodel.h>
#include <qgsdbfilterproxymodel.h>
#include <qgscolorschemeregistry.h>
#include <qgsfieldconstraints.h>
#include <labeling/qgslabellinesettings.h>
#include <labeling/qgslabelplacementsettings.h>
#include <labeling/qgslabeling.h>
#include <labeling/qgsrulebasedlabeling.h>
#include <labeling/qgsvectorlayerlabeling.h>
#include <labeling/qgslabelsearchtree.h>
#include <labeling/qgspallabeling.h>
#include <labeling/qgslabelthinningsettings.h>
#include <labeling/qgslabelingenginesettings.h>
#include <labeling/qgslabelingresults.h>
#include <labeling/qgscalloutposition.h>
#include <labeling/qgslabelobstaclesettings.h>
#include <labeling/qgslabelposition.h>
#include <qgssimplifymethod.h>
#include <annotations/qgsannotation.h>
#include <annotations/qgsannotationitemeditoperation.h>
#include <annotations/qgsannotationitemnode.h>
#include <annotations/qgsannotationpolygonitem.h>
#include <annotations/qgsrenderedannotationitemdetails.h>
#include <annotations/qgssvgannotation.h>
#include <annotations/qgshtmlannotation.h>
#include <annotations/qgsannotationitem.h>
#include <annotations/qgsannotationmarkeritem.h>
#include <annotations/qgstextannotation.h>
#include <annotations/qgsannotationlineitem.h>
#include <annotations/qgsannotationlinetextitem.h>
#include <annotations/qgsannotationpointtextitem.h>
#include <annotations/qgsannotationlayer.h>
#include <annotations/qgsannotationitemregistry.h>
#include <annotations/qgsannotationmanager.h>
#include <qgsdatasourceuri.h>
#include <qgstemporalnavigationobject.h>
#include <qgsabstractcontentcache.h>
#include <qgsreadwritecontext.h>
#include <qgsdatadefinedsizelegend.h>
#include <qgsexpressioncontext.h>
#include <qgstemporalproperty.h>
#include <qgsscaleutils.h>
#include <qgsmessagelog.h>
#include <qgscredentials.h>
#include <qgspaintenginehack.h>
#include <qgsaggregatecalculator.h>
#include <qgsmaplayerproxymodel.h>
#include <qgsfeaturefiltermodel.h>
#include <qgsobjectcustomproperties.h>
