version: '3'
services:

# Proving very fragile!
#  mssql:
#    image: microsoft/mssql-server-linux:2017-latest
#    environment:
#      ACCEPT_EULA: Y
#      SA_PASSWORD: <YourStrong!Passw0rd>

  webdav:
    image: nginx
    volumes:
      - ${GH_WORKSPACE}/.docker/webdav/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${GH_WORKSPACE}/.docker/webdav/passwords.list:/etc/nginx/.passwords.list
      - /tmp/webdav_tests:/tmp/webdav_tests_root/webdav_tests

  qgis-deps:
    tty: true
    image: qgis/qgis3-build-deps-bin-only:${DOCKER_TAG}
    volumes:
      - ${GH_WORKSPACE}:/root/QGIS
    links:
      - webdav
    #  - mssql
    env_file:
      - docker-variables.env
